# must be created first using the command kubectl apply -f mongo-secret.yaml
# then use kubectl applu -f mongo.yaml to deploy the mongodb

#to make sure the secret was created, use: kubectl get secret
#NAME           TYPE     DATA   AGE
#mongo-secret   Opaque   2      164m

apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-root-username: dXNlcm5hbWU= # "username" converted to base64
  mongo-root-password: cGFzc3dvcmQ= # "password" converted to base64