apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingapi-deployment
  labels:
    app: shoppingapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shoppingapi
  template:
    metadata:
      labels:
        app: shoppingapi
    spec:
      containers:
        - name: shoppingapi
          image: assismarcos/shoppingapi:latest #image pulled from docker hub
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: DatabaseSettings__ConnectionString #variable required by the shopping api to connect to mongodb. appsettings.json -> DatabaseSettings:ConnectionString
              valueFrom:
                configMapKeyRef: # reference to mongo-configmap.yaml
                  name: mongo-configmap
                  key: connection-string
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: shoppingapi-service
spec:
  type: NodePort
  selector:
    app: shoppingapi
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80
      nodePort: 31000 #port number to invoke the application from external systems, like Postman

# to check the port numbers, use: kubectl get svc
#NAME                     TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
#kubernetes               ClusterIP   10.96.0.1        <none>        443/TCP          18h
#mongo-service            ClusterIP   10.107.80.201    <none>        27017/TCP        175m
#shoppingapi-service      NodePort    10.99.180.115    <none>        8000:31000/TCP   34m
#shoppingclient-service   NodePort    10.101.120.218   <none>        8001:30000/TCP   13m